[env]
TERM = "xterm-256color"

[cursor.style]
shape = "Beam"
blinking = "On"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.9
blur = true

[font]
size = 14.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[general]
import = ["~/.config/alacritty/themes/themes/tokyo_night.toml"]

[terminal.shell]
program = "/opt/homebrew/bin/fish"
